---
env:
  node: true
  browser: true
  es2024: true

extends:
  - airbnb-base
  - react-app
  - "plugin:prettier/recommended"

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  no-console: off
  import/prefer-default-export: off
  import/extensions:
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle:
    - error
    - allow:
        - __filename
        - __dirname
